import logging
import os
import re
from pathlib import Path

from src.myvocab.parsing.vocabulary import vocabulary as vcb
from src.myvocab.parsing.commands.load_settings import load_settings
from src.myvocab.parsing.commands.write_settings import write_settings
from src.myvocab.parsing.commands.write_all_patches import write_all_patches
from src.myvocab.parsing.commands.write_directories import write_directories
from src.myvocab.parsing.commands.save_file import save_file
from src.myvocab.parsing.commands.diff_two_files import diff_two_files
from src.myvocab.parsing.commands.transformer.get_init_data import get_init_data
from src.myvocab.parsing.commands.skip_current_dir import skip_current_dir
from src.myvocab.parsing.commands.transformer.get_transformer import get_transformer, Transformer, add_pair
from src.myvocab.parsing.commands.transformer.log_transformer import log_transformer
from src.myvocab.utils.walk_handler.handle_error import handle_error
from src.myvocab.validators import validators as vld
from src.myvocab.exceptions import exceptions as exc
from src.myvocab.constants import constants as cns
from src.myvocab.parsing.infinitive import infinitive as inf
from src.myvocab.translation.translator import translate
from src.myvocab.authentication.auth_yandex.function_iam.fetch_iam_func import fetch_iam_func
from src.myvocab.authentication.auth_yandex.account_iam.fetch_iam_oauth import fetch_iam_oauth
# from src.myvocab.authentication.auth_yandex.exchange_jwt_iam.create_iam_token import create_iam_token

logger = logging.getLogger(__name__)


def remove_translation_marks(items: list) -> list:
    """ Remove translation tags. """
    return_items = list(items)
    for index, item in enumerate(items):
        if find_list := re.findall(f'{cns.TAG_TRANSLATE}(.+)', item):
            return_items[index] = find_list[0]
    return return_items


def render_vocab(base_path: Path) -> None:
    """ Generate a vocabulary from the base directory.

    Any text outside the `<<word>>` and `<</word>>` tag-only strings is treated as raw file lines.
    Text enclosed in `<<word>>` and `<</word>>` tag-only strings is interpreted as a list of isolated English words,
    which can optionally be converted to their singular or infinitive forms, or a specified case, and translated into supported languages.
    Configure the options in the auto-generated `settings.txt` file, located in the `base_directory/Myvocab_58b254sv/` directory.
    This directory holds all the output data generated by the program.

    Args:
        base_path (Path): Path to the base directory.
    """

    # Create a new empty vocabulary
    vocab = vcb.VocabConfig(base_path)
    # Load settings from an existing file, otherwise persist defaults
    load_settings(vocab)

    # Add transformers
    if vocab.use_lemma_singular:
        vocab.set_singular(True)
    if vocab.use_lemma_infinit:
        vocab.set_infinitive(True)
    if vocab.use_lemma_casing:
        vocab.set_casing(True)

    # Get the list of verbs ending in -s
    verbs_s = set()
    if vocab.use_lemma_singular:
        # Get a list of irregular verbs ending in -s from the project files
        verbs_s.update(inf.InfinitAttrib.infinit_attrib_verbs_ending_s())
        if vocab.use_lemma_infinit:
            # and merge them with those stored in the Documents directory
            verbs_s.update(vocab.infinit.verbs_ending_s())
    vocab.verbs_ending_s = verbs_s

    logger.debug(vocab)

    # Persist settings to a file
    write_settings(vocab)

    write_all_patches(vocab)
    write_directories(vocab)

    parsed_pairs = {
        Transformer.SINGULAR: set(),
        Transformer.INFINITE: set(),
        Transformer.CASING: set()
    }

    lines_list = list()
    lines_set = set()

    # Caching transformations for reuse
    transform_dict = dict()
    # Caching translations for reuse
    translated_words = dict()

    trn_tag = ""
    if vocab.use_word_translate:
        # Tag for translation
        trn_tag = cns.TAG_TRANSLATE
        logger.info("Translation direction: " +
                    f"`{vocab.source_language}` to `{vocab.target_language}` " +
                    f"(`{vocab.source_language_code}` -> `{vocab.target_language_code}`)")

    logger.info("Populating a new vocabulary with isolated words and phrases ...")
    offset = len(vocab.base_directory.parts) - 1
    # If the PyInstaller executable sets the base directory to '.'
    if offset < 0:
        offset = 0

    # Show the `activity indicator`
    print("Parsing files: ", end="", flush=True)

    flag_next_file = False

    # Path.walk traverses the directory tree, starting from the base
    for dirpath, dirs, files in Path.walk(vocab.base_directory, on_error=handle_error):

        # The path is starting from the base directory.
        dirpath_parts = Path(*dirpath.parts[offset::])

        # Check if the current directory should be ignored
        if skip_current_dir(vocab, dirpath, dirpath_parts):
            continue

        for filename in files:

            # Text files only
            if not filename.endswith(".txt"):
                continue

            try:
                # Ignore files prefixed with '!' if 'use_dir_with_leading_exclamation_mark' flag is unset
                join_path = Path.joinpath(dirpath_parts, filename)
                vld.validate_directory_with_leading_exclamation_mark(join_path,
                                                                     vocab.use_dir_with_leading_exclamation_mark)
            except exc.VocabError:
                continue

            filepath = Path.joinpath(dirpath, filename)
            # Keep the `activity indicator` visible
            print(".", end="", flush=True)

            file_lines = list()
            file_list = list()
            file_set = set()
            # First words of sentences that are capitalized, but allow for lowercase as well
            first_words = set()

            # Read the current file
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()

                # Extract the first words of sentences that are capitalized, but allow for lowercase as well
                if vocab.use_lemma_casing:
                    firsts = set()
                    firsts.update(re.findall(r'[.!?…—]["“”„]*[ \n]["“”„]*([A-Z][a-z0-9-]+)', content, re.MULTILINE))
                    # Extract all words from a text
                    alls = set()
                    alls.update(re.findall(r'\b[a-zA-Z0-9-]+\b', content, re.MULTILINE))
                    # Extract words that allow lowercase
                    for word in firsts:
                        cur_word = word.lower()
                        # If the text contains the word in lowercase
                        if cur_word in alls:
                            first_words.add(word)
                    # Remove processed words from the "firsts" set
                    for word in first_words:
                        firsts.remove(word)

                    if vocab.use_lemma_infinit or vocab.use_lemma_singular:
                        # Transform the remaining words and check if they can be added to the 'first_words' set.
                        logger.debug("Start transforming the words and adding some of them to the case set.")
                        for word in firsts:
                            if word[0].isupper():
                                trans_data = get_transformer(vocab, word, parsed_pairs)
                                if trans_data["id"] in cns.RANGE_CASING_ID:
                                    if trans_data["word"].lower() in alls:
                                        first_words.add(word)
                        logger.debug("Finish transforming the words and adding some of them to the case set.")

                # Read lines from a file
                file_lines = re.findall(r'[^\n]+', content)

            t_word = False
            if not vocab.use_order_text:

                file_delimiter = str(Path.joinpath(dirpath_parts, filename)).ljust(80, '-')
                if flag_next_file:
                    file_list.append(f"\n{file_delimiter}")
                else:
                    flag_next_file = True
                    file_list.append(f"{file_delimiter}")

            for file_line in file_lines:
                if file_line == cns.TAG_WORD:
                    t_word = True
                    continue
                elif file_line == cns.TAG_END_WORD:
                    t_word = False
                    continue

                # If the string containing only the tag cns.TAG_WORD is found
                if t_word:
                    file_line_words = re.findall(r'\b[a-zA-Z0-9-]+\b', file_line)

                    # Word processing using Transformers
                    for fl_word in file_line_words:

                        # Exclude numbers
                        if re.match(r'\b[0-9]+\b', fl_word):
                            continue

                        # Convert the word to lowercase
                        if fl_word in first_words:
                            fl_word = fl_word.lower()

                        if trans_val := transform_dict.get(fl_word):
                            val = trans_val
                        else:
                            # if the word contains a hyphen
                            is_multi = False
                            multi_words = re.split(r'-', fl_word)
                            if len(multi_words) > 1:
                                for m_word in multi_words:
                                    if m_word != "":
                                        # Enable hyphenated compound processing
                                        is_multi = True
                                        break
                            # Hyphenated compound
                            if is_multi:
                                trns_data_id = cns.UNCHANGED_DATA_ID
                                multi_phrase = ""

                                for multi_word in multi_words:
                                    if multi_word != "":

                                        # Convert the word to lowercase
                                        if multi_word in first_words:
                                            multi_word = multi_word.lower()

                                        if multi_phrase != "":
                                            multi_phrase += "-"

                                        if trans_val := transform_dict.get(multi_word):
                                            multi_val = trans_val
                                        else:
                                            trans_data = get_transformer(vocab, multi_word, parsed_pairs)
                                            if trans_data["id"] != cns.UNCHANGED_DATA_ID:
                                                trns_data_id = trans_data["id"]
                                            multi_val = trans_data["word"]
                                            transform_dict[multi_word] = multi_val

                                        multi_phrase = multi_phrase + multi_val

                                val = multi_phrase
                                if val != "" and val != fl_word:
                                    if trns_data_id != cns.UNCHANGED_DATA_ID:
                                        trans_data["id"] = trns_data_id
                                    else:
                                        trans_data["id"] = cns.RANGE_CASING_MAX_ID
                                    trans_data[
                                        "pair"] = "" if fl_word == multi_phrase else f"{fl_word} - {multi_phrase}"
                                    add_pair(parsed_pairs, trans_data)
                                    # Log a specific transform
                                    log_transformer(get_init_data(multi_phrase, trns_data_id),
                                                    f"{fl_word} -> {multi_phrase}")
                            else:
                                trans_data = get_transformer(vocab, fl_word, parsed_pairs)
                                val = trans_data["word"]
                                transform_dict[fl_word] = val

                        # The word has been processed
                        if vocab.use_order_text:
                            file_set.add(trn_tag + val)
                        else:
                            if val not in file_set:
                                file_list.append(trn_tag + val)
                                file_set.add(val)

                else:
                    file_line = file_line.strip()
                    if file_line != '':
                        if vocab.use_order_text:
                            file_set.add(file_line)
                        else:
                            if file_line not in file_set:
                                file_list.append(file_line)
                                file_set.add(file_line)

            if vocab.use_order_text:
                lines_set.update(file_set)
            else:
                lines_list.extend(file_list)

    if vocab.use_order_text:
        all_list = list(lines_set)
    else:
        all_list = list(lines_list)

    # Restore word wrap after using the activity indicator
    print("")

    if vocab.use_word_translate:

        auth = os.getenv('AUTH')
        logger.info(f"auth: {auth}")

        iam_token = None
        transl_words = None

        if auth == 'account_iam':
            # To get an IAM token with a Yandex account
            vdata = fetch_iam_oauth()
            if vdata.get("ok") and (iam_token := vdata.get("iamToken")):
                transl_words = None if vocab.use_order_text else translated_words
            else:
                all_list = remove_translation_marks(all_list)
                logger.error("Failed to fetch IAM token while preparing to translate.")
        elif auth == 'exchange_jwt_iam':
            # To get an IAM token with an Authorized keys.
            try:
                iam_token = create_iam_token()
                transl_words = None if vocab.use_order_text else translated_words
            except Exception as e:
                all_list = remove_translation_marks(all_list)
                logger.error(f"Failed to fetch IAM token while preparing to translate: {e}")
        else:
            # To get an IAM token from the function code in Yandex Cloud Functions
            vdata = fetch_iam_func()
            if iam_token := vdata.get("access_token"):
                transl_words = None if vocab.use_order_text else translated_words
            else:
                all_list = remove_translation_marks(all_list)
                logger.error("Failed to fetch IAM token while preparing to translate.")

        if iam_token is not None and iam_token != "":
            all_list = translate(
                iam=iam_token,
                words=all_list,
                target_language_code=vocab.target_language_code,
                result_directory=vocab.result_file.parent,
                translated_words=transl_words)
    else:
        # Delete both the sent and received API translation files
        translate_path = Path.joinpath(vocab.result_directory, cns.TRANSLATE_FOLDER)
        if translate_path.exists() and translate_path.is_dir():
            # Loop through and delete files only
            for file_path in translate_path.iterdir():
                if file_path.is_file():
                    file_path.unlink()

    # Vocabulary
    if not vocab.result_file.is_file():
        vocab.result_file.parent.mkdir(exist_ok=True, parents=True)
    # Write the vocabulary to a file
    save_file(vocab.result_file, all_list, vocab.use_order_text)
    logger.info(f"The resulting vocabulary has been created: \n{vocab.result_file.resolve()}")

    # Singularization
    if vocab.use_lemma_singular:
        # Write all pairs of original plural words and their singularized versions to the `singular.parsed_pairs_path` directory.
        save_file(vocab.singular.parsed_pairs_path, list(parsed_pairs[Transformer.SINGULAR]), vocab.use_order_text)

        # This allows the user to potentially analyze the applied transformations.
        # Some or all transformations validated by the user may be copied to the `singular.reviewed_pairs_path` directory.

        # Get the remaining unverified transformation.
        unreviewed_pairs = diff_two_files(vocab.singular.parsed_pairs_path, vocab.singular.reviewed_pairs_path)
        # Write the remaining unverified transformation to the `singular.unreviewed_pairs_path` directory.
        save_file(vocab.singular.unreviewed_pairs_path, unreviewed_pairs, vocab.use_order_text)
    else:
        # Save empty files
        if vocab.singular is None:
            vocab.set_singular(False)
        save_file(vocab.singular.parsed_pairs_path, list(), False)
        save_file(vocab.singular.unreviewed_pairs_path, list(), False)

    # Infinitive
    if vocab.use_lemma_infinit:
        # Write all pairs of original words and their base forms to the infinit.`infinit.parsed_pairs_path` directory.
        save_file(vocab.infinit.parsed_pairs_path, list(parsed_pairs[Transformer.INFINITE]), vocab.use_order_text)

        # This allows the user to potentially analyze the applied transformations.
        # Some or all transformations validated by the user may be copied to the `infinit.reviewed_pairs_path` directory.

        # Get the remaining unverified transformation.
        unreviewed_pairs = diff_two_files(vocab.infinit.parsed_pairs_path, vocab.infinit.reviewed_pairs_path)
        # Write the remaining unverified transformation to the `infinit.unreviewed_pairs_path` directory.
        save_file(vocab.infinit.unreviewed_pairs_path, unreviewed_pairs, vocab.use_order_text)
    else:
        # Save empty files
        if vocab.infinit is None:
            vocab.set_infinitive(False)
        save_file(vocab.infinit.parsed_pairs_path, list(), False)
        save_file(vocab.infinit.unreviewed_pairs_path, list(), False)

    # Casing
    if vocab.use_lemma_casing:
        # Write all pairs of original words and their casing forms to the casing.`casing.parsed_pairs_path` directory.
        save_file(vocab.casing.parsed_pairs_path, list(parsed_pairs[Transformer.CASING]), vocab.use_order_text)

        # This allows the user to potentially analyze the applied transformations.
        # Some or all transformations validated by the user may be copied to the `casing.reviewed_pairs_path` directory.

        # Get the remaining unverified transformation.
        unreviewed_pairs = diff_two_files(vocab.casing.parsed_pairs_path, vocab.casing.reviewed_pairs_path)
        # Write the remaining unverified transformation to the `casing.unreviewed_pairs_path` directory.
        save_file(vocab.casing.unreviewed_pairs_path, unreviewed_pairs, vocab.use_order_text)
    else:
        # Save empty files
        if vocab.casing is None:
            vocab.set_casing(False)
        save_file(vocab.casing.parsed_pairs_path, list(), False)
        save_file(vocab.casing.unreviewed_pairs_path, list(), False)
